### PR TITLE
Update(s)

### PR DESCRIPTION
**Pull request by DamieFC**
Don't merge yet, I might add more tomorrow (it's 8 PM rn)

### CODE REVIEW

**Comment by jmerono-saez** [comment]
I mean, thanks for wanting to contribute, but the shell is something I wanna get working myself, and then let people add stuff to it. Also, changing the prompt to "nop>" is something completely subjective, and I don't like it that much.

**Comment by DamieFC** [comment]
Ok. will remove. Also, should I try adding the cursed NMI again or should I forget it.

**Comment by jmerono-saez** [comment]
> Ok. will remove. Also, should I try adding the cursed NMI again or should I forget it.

Meh, just forget about NMI, like almost no OS even changes that, and it isn't that important. Oh and I pushed some new changes with a new prompt and a better shell, please check it out.

**Comment by DamieFC** [comment]
I checked it out, and I like the new prompt. I think I'll just close this, seeing as I don't have any new ideas for what to add.

**Comment by DamieFC** [comment]
UNLESS YOU WANT ME TO TRY TO ADD A NEW DRIVER OR SOMETHING why am I yelling.

**Pull request closed without merging**
